config/routes.rb
Rails.application.routes.draw do
  get 'tool/upload'
  post 'tool/zip'
  get 'tool/download'

  resources :genres

  resources :sale_categories

  resources :prices

  resources :sale_products

  get 'sales/:id/link' => 'sales#link', :as => 'link_sale'
  patch'sales/:id/update_product' => 'sales#update_product', :as => 'update_product'
  resources :sales

  resources :products

  devise_for :users

  get 'tasks/download_thumb' => 'tasks#download_thumb', :as => 'download_thumb'
  get 'tasks/download_data' => 'tasks#download_data', :as => 'download_data'
  get 'tasks/:id/link' => 'tasks#link', :as => 'link_to_sale'
  patch 'tasks/:id/update_sale' => 'tasks#update_sale', :as => 'link_to_update_sale'
  get 'tasks/:id/release' => 'tasks#release', :as => 'release_task'
  resources :tasks

  root 'tasks#index'

end

app/models/sale_category.rb
class SaleCategory < ActiveRecord::Base
end

app/controllers/sale_categories_controller.rb
class SaleCategoriesController < ApplicationController
  before_action :set_sale_category, only: [:show, :edit, :update, :destroy]

  # GET /sale_categories
  # GET /sale_categories.json
  def index
    @sale_categories = SaleCategory.all
  end

  # GET /sale_categories/1
  # GET /sale_categories/1.json
  def show
  end

  # GET /sale_categories/new
  def new
    @sale_category = SaleCategory.new
  end

  # GET /sale_categories/1/edit
  def edit
  end

  # POST /sale_categories
  # POST /sale_categories.json
  def create
    @sale_category = SaleCategory.new(sale_category_params)

    respond_to do |format|
      if @sale_category.save
        format.html { redirect_to @sale_category, notice: 'Sale category was successfully created.' }
        format.json { render :show, status: :created, location: @sale_category }
      else
        format.html { render :new }
        format.json { render json: @sale_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sale_categories/1
  # PATCH/PUT /sale_categories/1.json
  def update
    respond_to do |format|
      if @sale_category.update(sale_category_params)
        format.html { redirect_to @sale_category, notice: 'Sale category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale_category }
      else
        format.html { render :edit }
        format.json { render json: @sale_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_categories/1
  # DELETE /sale_categories/1.json
  def destroy
    @sale_category.destroy
    respond_to do |format|
      format.html { redirect_to sale_categories_url, notice: 'Sale category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale_category
      @sale_category = SaleCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_category_params
      params.require(:sale_category).permit(:name, :label, :last_id)
    end
end

app/helpers/sale_categories_helper.rb
module SaleCategoriesHelper
end

app/views/sale_categories/_form.html.haml
= form_for @sale_category, :html => { :class => 'form-horizontal' } do |f|
  - if @sale_category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale_category.errors.count, 'error')} prohibited this product from being saved:"
      %ul
        - @sale_category.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :label, :class => 'control-label'
    .controls
      = f.text_field :label, :class => 'form-control'
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), sale_categories_path, :class => 'btn btn-default'

app/views/sale_categories/edit.html.haml
- model_class = SaleCategory
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/sale_categories/index.html.haml
- model_class = SaleCategory
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:label)
      %th= model_class.human_attribute_name(:last_id)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @sale_categories.each do |sale_category|
      %tr
        %td= link_to sale_category.id, sale_category_path(sale_category)
        %td= sale_category.name
        %td= sale_category.label
        %td= sale_category.last_id
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_sale_category_path(sale_category), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), sale_category_path(sale_category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_sale_category_path, :class => 'btn btn-primary'

app/views/sale_categories/new.html.haml
- model_class = SaleCategory
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/sale_categories/show.html.haml
- model_class = SaleCategory
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @sale_category.name
%p
  %strong= model_class.human_attribute_name(:label) + ':'
  %br
  = @sale_category.label
%p
  %strong= model_class.human_attribute_name(:last_id) + ':'
  %br
  = @sale_category.last_id


= link_to t('.back', :default => t("helpers.links.back")), sale_categories_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_sale_category_path(@sale_category), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), sale_category_path(@sale_category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'