config/routes.rb
Rails.application.routes.draw do
  get 'tool/upload'
  post 'tool/zip'
  get 'tool/download'

  resources :genres

  resources :sale_categories

  resources :prices

  resources :sale_products

  get 'sales/:id/link' => 'sales#link', :as => 'link_sale'
  patch'sales/:id/update_product' => 'sales#update_product', :as => 'update_product'
  resources :sales

  resources :products

  devise_for :users

  get 'tasks/download_thumb' => 'tasks#download_thumb', :as => 'download_thumb'
  get 'tasks/download_data' => 'tasks#download_data', :as => 'download_data'
  get 'tasks/:id/link' => 'tasks#link', :as => 'link_to_sale'
  patch 'tasks/:id/update_sale' => 'tasks#update_sale', :as => 'link_to_update_sale'
  get 'tasks/:id/release' => 'tasks#release', :as => 'release_task'
  resources :tasks

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :sales

  attr_accessor :sale_id

  def app_type_choices
    [
      ['赤', 0],
      ['青', 1]
    ]
  end

  def paid_choices
    [
      ['無料', 0],
      ['有料', 1]
    ]
  end

  def sql
    #MEMO nakao rubyで'\n'は改行でない
    product_sql = "-- ↓↓↓↓↓for mtb_product↓↓↓↓↓\n"
    package_sql = "-- ↓↓↓↓↓for dtb_package↓↓↓↓↓\n"
    sale_sql = "-- ↓↓↓↓↓for mtb_sale↓↓↓↓↓\n"
    self.sales.each do |sale|
      sale_sql += sale.sql
      sale.products.each do |sale_product|
        package_sql += sale_product.sql
        product_sql += Product.where(:id => sale_product.product_id)[0].sql
      end
    end
    product_sql += "\n-- ↑↑↑↑↑for mtb_product↑↑↑↑↑\n\n"
    package_sql += "\n-- ↑↑↑↑↑for dtb_package↑↑↑↑↑\n\n"
    sale_sql += "\n-- ↑↑↑↑↑for mtb_sale↑↑↑↑↑\n\n"
    product_sql + package_sql + sale_sql
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :release, :link, :update_sale]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  def release
    @sql = @task.sql
  end

  def download_data
    dest = File.join(Rails.root, 'var', 'tmp', 'data.zip')
    Utils.zip(File.join(Rails.root, 'var', 'data'), dest)
    send_file(dest)
  end

  def download_thumb
    dest = File.join(Rails.root, 'var', 'tmp', 'thumb.zip')
    Utils.zip(File.join(Rails.root, 'var', 'thumb'), dest)
    send_file(dest)
  end

  def link
  end

  def update_sale
    #TODO nakao params[:task][:sale_id]のvalidation check
    respond_to do |format|
      sale = Sale.find(params[:task][:sale_id])
      if sale.update_attributes(:task_id => @task.id)
        format.html { render :linked, notice: 'Task_id was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :user_id, :app_type, :paid, :release_at)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for @task, :html => { :class => 'form-horizontal' } do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, 'error')} prohibited this product from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'form-control'
  .form-group
    = f.label :app_type, :class => 'control-label'
    .controls
      = f.select :app_type, @task.app_type_choices, :class => 'form-control'
  .form-group
    = f.label :paid, :class => 'control-label'
    .controls
      = f.select :paid, @task.paid_choices, :class => 'form-control'
  .form-group
    = f.label :release_at, :class => 'control-label'
    .controls
      = f.text_field :release_at, :class => 'form-control'
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn btn-default'

app/views/tasks/edit.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tasks/index.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:app_type)
      %th= model_class.human_attribute_name(:paid)
      %th= model_class.human_attribute_name(:release_at)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to task.id, task_path(task)
        %td= task.name
        %td= task.description
        %td= task.user.username
        %td= task.app_type
        %td= task.paid
        %td= task.release_at
        %td=l task.created_at
        %td
          = link_to t('.release', :default => t("helpers.links.link_sale")), link_to_sale_path(task), :class => 'btn btn-success btn-xs'
          = link_to t('.release', :default => t("helpers.links.release")), release_task_path(task), :class => 'btn btn-success btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(task), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(task), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_task_path, :class => 'btn btn-primary'

app/views/tasks/link.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.link', 'Link %{model}'], :model => model_class.model_name.human.titleize
= form_for @task, :html => { :class => 'form-horizontal' }, :url => { :action => 'update_sale'} do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale.errors.count, 'error')} prohibited this product from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg
  = f.label "#{@task.name} に対して紐付けする販売を選択"
  .form-group
    = f.label :sale_id, :class => 'control-label'
    .controls
      = f.select :sale_id, Sale.where.not(:task_id == @task.id).pluck(:name, :id), :class => 'form-control'
  = f.submit t("helpers.links.link_sale"), :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), tasks_path, :class => 'btn btn-default'

app/views/tasks/linked.html.haml
.page-header
  %h1 タスクに紐付けられた販売名

%p
  %strong= 'タスク名'
  %br
  = @task.name

- Sale.where(:task_id => @task.id).each_with_index do |sale, i|
  %p
    %strong= "紐付けられた販売名 #{i+1}"
    %br
    = sale.name
= link_to t('.back', :default => t("helpers.links.back")), tasks_path, :class => 'btn btn-default'

app/views/tasks/new.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/tasks/release.html.haml
%pre
  %code= @sql
= link_to t('.back', :default => t("helpers.links.download_thumb")), download_thumb_path, :class => 'btn btn-success'
= link_to t('.back', :default => t("helpers.links.download_data")), download_data_path, :class => 'btn btn-success'
= link_to t('.back', :default => t("helpers.links.back")), tasks_path, :class => 'btn btn-default'

app/views/tasks/show.html.haml
- model_class = Task
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @task.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @task.description
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @task.user_id
%p
  %strong= model_class.human_attribute_name(:app_type) + ':'
  %br
  = @task.app_type
%p
  %strong= model_class.human_attribute_name(:paid) + ':'
  %br
  = @task.paid
%p
  %strong= model_class.human_attribute_name(:release_at) + ':'
  %br
  = @task.release_at


= link_to t('.back', :default => t("helpers.links.back")), tasks_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_task_path(@task), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), task_path(@task), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'