config/routes.rb
Rails.application.routes.draw do
  get 'tool/upload'
  post 'tool/zip'
  get 'tool/download'

  resources :genres

  resources :sale_categories

  resources :prices

  resources :sale_products

  get 'sales/:id/link' => 'sales#link', :as => 'link_sale'
  patch'sales/:id/update_product' => 'sales#update_product', :as => 'update_product'
  resources :sales

  resources :products

  devise_for :users

  get 'tasks/download_thumb' => 'tasks#download_thumb', :as => 'download_thumb'
  get 'tasks/download_data' => 'tasks#download_data', :as => 'download_data'
  get 'tasks/:id/link' => 'tasks#link', :as => 'link_to_sale'
  patch 'tasks/:id/update_sale' => 'tasks#update_sale', :as => 'link_to_update_sale'
  get 'tasks/:id/release' => 'tasks#release', :as => 'release_task'
  resources :tasks

  root 'tasks#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :task
  has_many :sale_products
  has_many :products, :through => :sale_products  
  belongs_to :price
  belongs_to :sale_category
  before_create :set_default_value

  attr_accessor :thumbnail_file, :preview1_file, :preview2_file, :preview3_file, :preview4_file, :preview5_file, :product_id

  validates :name, :price_id,:sale_category_id, :display_order, :is_new, presence: true
  validates :thumbnail_file, :preview1_file, presence: true, on: :create
  validates :name, allow_blank: true, uniqueness: true
  validates :price_id, :sale_category_id, :display_order, allow_blank: true, numericality: true
  validates :thumbnail_file, allow_blank: true, extension: {:white_list => %w(bmp gif jpg jpeg png)}
  validates :preview1_file, allow_blank: true, extension: {:white_list => %w(bmp gif jpg jpeg png)}
  validates :preview2_file, allow_blank: true, extension: {:white_list => %w(bmp gif jpg jpeg png)}
  validates :preview3_file, allow_blank: true, extension: {:white_list => %w(bmp gif jpg jpeg png)}
  validates :preview4_file, allow_blank: true, extension: {:white_list => %w(bmp gif jpg jpeg png)}
  validates :preview5_file, allow_blank: true, extension: {:white_list => %w(bmp gif jpg jpeg png)}

  SALE_AREA_RED = 0
  SALE_AREA_BLUE = 1

  ENTRY_PLAN_RED = 0
  STANDARD_PLAN_RED = 1
  PREMIUM_PLAN_RED = 2
  RIGHT_PLAN_BLUE = 3
  PRO_PLAN_BLUE = 4

  def price_choices
    Price.pluck(:value, :id)
  end

  def sale_category_choices
    SaleCategory.pluck(:name, :id)
  end

  def is_new_choices
    [['新着フラグをだす', true],
     ['新着フラグをださない', false]]
  end

  def sql
    'INSERT INTO mtb_sale VALUES'\
      + "('#{label_id}', '#{name}', NULL, #{Price.find(price_id).value}, '#{SaleCategory.find(sale_category_id).label}', "\
      + "#{display_order}, #{thumbnail_url}, #{form(preview1_url)}, #{form(preview2_url)}, #{form(preview3_url)}, "\
      + "#{form(preview4_url)}, #{form(preview5_url)}, true, true, #{is_new}, 0, '2');"
  end

  private

    def next_label
      count_up current_label
    end

    def count_up(label)
      counter = label[-5, 5].to_i(10)
      SaleCategory.find(sale_category_id).label + format('%05d', counter + 1)
    end

    def current_label
      first = Sale.where(sale_category_id: sale_category_id).order('label_id DESC').first
      if first
        first.label_id
      else
        SaleCategory.where(id: sale_category_id).pluck(:last_id).first
      end
    end

    def set_default_value
      self.label_id = next_label
      self.description ||= nil
      self.visible ||= true
      self.area ||= SALE_AREA_RED
      self.optimum_plan ||= PREMIUM_PLAN_RED
      self.task_id = nil
    end

    def form(value)
      if value == nil || value == ''
        'NULL'
      else
        "'#{value}'"
      end
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy, :link, :update_product]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  def link
  end

  def update_product
    #TODO nakao params[:sale][:product_id]のvalidation check
    sale_product = SaleProduct.new({:sale_id => @sale.id, :product_id => params[:sale][:product_id]})
    respond_to do |format|
      if sale_product.save
        format.html { render :linked, notice: 'Task_id was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:name, :price_id, :sale_category_id, :display_order, :thumbnail_file, :preview1_file, :preview2_file, :preview3_file, :preview4_file, :preview5_file, :is_new)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.haml
= form_for @sale, :html => { :class => 'form-horizontal' } do |f|
  - if @sale.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale.errors.count, 'error')} prohibited this product from being saved:"
      %ul
        - @sale.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :price_id, :class => 'control-label'
    .controls
      = f.select :price_id, @sale.price_choices, :class => 'form-control'
  .form-group
    = f.label :sale_category_id, :class => 'control-label'
    .controls
      = f.select :sale_category_id, @sale.sale_category_choices, :class => 'form-control'
  .form-group
    = f.label :display_order, :class => 'control-label'
    .controls
      = f.text_field :display_order, :class => 'form-control'
  .form-group
    = f.label :thumbnail_file, :class => 'control-label'
    .controls
      = f.file_field :thumbnail_file, :accept => 'image/*', :class => 'form-control'
  .form-group
    = f.label :preview1_file, :class => 'control-label'
    .controls
      = f.file_field :preview1_file, :accept => 'image/*', :class => 'form-control'
  .form-group
    = f.label :preview2_file, :class => 'control-label'
    .controls
      = f.file_field :preview2_file, :accept => 'image/*', :class => 'form-control'
  .form-group
    = f.label :preview3_file, :class => 'control-label'
    .controls
      = f.file_field :preview3_file, :accept => 'image/*', :class => 'form-control'
  .form-group
    = f.label :preview4_file, :class => 'control-label'
    .controls
      = f.file_field :preview4_file, :accept => 'image/*', :class => 'form-control'
  .form-group
    = f.label :preview5_file, :class => 'control-label'
    .controls
      = f.file_field :preview5_file, :accept => 'image/*', :class => 'form-control'
  .form-group
    = f.label :is_new, :class => 'control-label'
    .controls
      = f.select :is_new, @sale.is_new_choices, :class => 'form-control'
  = f.submit nil, :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), sales_path, :class => 'btn btn-default'

app/views/sales/edit.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/sales/index.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:label_id)
      %th= model_class.human_attribute_name(:price_id)
      %th= model_class.human_attribute_name(:sale_category_id)
      %th= model_class.human_attribute_name(:display_order)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @sales.each do |sale|
      %tr
        %td= link_to sale.id, sale_path(sale)
        %td= sale.name
        %td= sale.label_id
        %td= sale.price.value
        %td= sale.sale_category.name
        %td= sale.display_order
        %td
          = link_to t('.link', :default => t("helpers.links.link_product")), link_sale_path(sale), :class => 'btn btn-success btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_sale_path(sale), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), sale_path(sale), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_sale_path, :class => 'btn btn-primary'

app/views/sales/link.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => [:'helpers.titles.link', 'Link %{model}'], :model => model_class.model_name.human.titleize
= form_for @sale, :html => { :class => 'form-horizontal' }, :url => { :action => 'update_product'} do |f|
  - if @sale.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sale.errors.count, 'error')} prohibited this product from being saved:"
      %ul
        - @sale.errors.full_messages.each do |msg|
          %li= msg
  = f.label "#{@sale.name} に対して紐付けする素材を選択"
  .form-group
    = f.label :product_id, :class => 'control-label'
    .controls
      = f.select :product_id, Product.pluck(:name, :id), :class => 'form-control'
  = f.submit t("helpers.links.link_product"), :class => 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), sales_path, :class => 'btn btn-default'

app/views/sales/linked.html.haml
.page-header
  %h1 販売に紐付けられた素材名

%p
  %strong= '販売名'
  %br
  = @sale.name

- SaleProduct.where(:sale_id => @sale.id).each_with_index do |sale_product, i|
  %p
    %strong= "紐付けられた素材名 #{i+1}"
    %br
    = Product.find(sale_product.product_id).name
= link_to t('.back', :default => t("helpers.links.back")), sales_path, :class => 'btn btn-default'

app/views/sales/new.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/sales/show.html.haml
- model_class = Sale
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @sale.name
%p
  %strong= model_class.human_attribute_name(:label_id) + ':'
  %br
  = @sale.label_id
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @sale.description
%p
  %strong= model_class.human_attribute_name(:display_order) + ':'
  %br
  = @sale.display_order
%p
  %strong= model_class.human_attribute_name(:thumbnail_url) + ':'
  %br
  = @sale.thumbnail_url
%p
  %strong= model_class.human_attribute_name(:preview1_url) + ':'
  %br
  = @sale.preview1_url
%p
  %strong= model_class.human_attribute_name(:preview2_url) + ':'
  %br
  = @sale.preview2_url
%p
  %strong= model_class.human_attribute_name(:preview3_url) + ':'
  %br
  = @sale.preview3_url
%p
  %strong= model_class.human_attribute_name(:preview4_url) + ':'
  %br
  = @sale.preview4_url
%p
  %strong= model_class.human_attribute_name(:preview5_url) + ':'
  %br
  = @sale.preview5_url
%p
  %strong= model_class.human_attribute_name(:visible) + ':'
  %br
  = @sale.visible
%p
  %strong= model_class.human_attribute_name(:approval_at) + ':'
  %br
  = @sale.approval_at
%p
  %strong= model_class.human_attribute_name(:is_new) + ':'
  %br
  = @sale.is_new
%p
  %strong= model_class.human_attribute_name(:area) + ':'
  %br
  = @sale.area
%p
  %strong= model_class.human_attribute_name(:optimum_plan) + ':'
  %br
  = @sale.optimum_plan
%p
  %strong= model_class.human_attribute_name(:task_id) + ':'
  %br
  = @sale.task_id
%p
  %strong= model_class.human_attribute_name(:price_id) + ':'
  %br
  = @sale.price_id
%p
  %strong= model_class.human_attribute_name(:sale_category_id) + ':'
  %br
  = @sale.sale_category_id


= link_to t('.back', :default => t("helpers.links.back")), sales_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_sale_path(@sale), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), sale_path(@sale), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'