config/routes.rb
Rails.application.routes.draw do
  get 'tool/upload'
  post 'tool/zip'
  get 'tool/download'

  resources :genres

  resources :sale_categories

  resources :prices

  resources :sale_products

  get 'sales/:id/link' => 'sales#link', :as => 'link_sale'
  patch'sales/:id/update_product' => 'sales#update_product', :as => 'update_product'
  resources :sales

  resources :products

  devise_for :users

  get 'tasks/download_thumb' => 'tasks#download_thumb', :as => 'download_thumb'
  get 'tasks/download_data' => 'tasks#download_data', :as => 'download_data'
  get 'tasks/:id/link' => 'tasks#link', :as => 'link_to_sale'
  patch 'tasks/:id/update_sale' => 'tasks#update_sale', :as => 'link_to_update_sale'
  get 'tasks/:id/release' => 'tasks#release', :as => 'release_task'
  resources :tasks

  root 'tasks#index'

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Yakitori"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/")= t('top.home')
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to Product.model_name.human.pluralize.titleize, products_path
            %li= link_to Sale.model_name.human.pluralize.titleize, sales_path
            %li= link_to Task.model_name.human.pluralize.titleize, tasks_path
            - if user_signed_in?
              %li= link_to t('top.logout'), destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" }


    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            %h3= t('top.settings')
            %ul.nav.nav-list
              %li= link_to Price.model_name.human.pluralize.titleize, prices_path
              %li= link_to SaleCategory.model_name.human.pluralize.titleize, sale_categories_path
              %li= link_to Genre.model_name.human.pluralize.titleize, genres_path
            %h4= t('top.tools')
            %ul.nav.nav-list
              %li= link_to t('tool_action.zip'), tool_upload_path
      %footer
        %p &copy; Company 2014